on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ALpotato/zmk/.github/workflows/build-user-config.yml@ptdevice-alpotato
 - name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: '20.0.0'
